### ISSUE TITLE
Not working with Sketch 3.3.2

### ISSUE THREAD

**Issue by victordarras** [maundytime/sketch-9patch#1]
Hi, it seems that the plugin is not working on the last version of Sketch, I didn't use it before so it's maybe my fault. I'll try to read the plugin code later, to see if I can help you.

**Comment by alookat** [comment]
Second this. Also, I'm not really sure how to use this plugin (once working). Are groups meant to be labelled "$MarksGroup"? Or should a .9.png option appear under the export formats dropdown? Thanks

**Comment by maundytime** [comment]
Bug fixed.

[[layer absoluteRect] expandBy] not working, I Google it but no result. And
I use other method instead to fix it. See code blow:

// [[artboard absoluteRect] expandBy:1]; // This not work in new version
> Sketch!
>     rectOriginal = getRect(artboard);
>     setSize(artboard, rectOriginal.width+2, rectOriginal.height+2, 1);


Thanks for telling me that, now plugin work again, check
https://github.com/maundytime/sketch-9patch please :)





2015-05-18 15:53 GMT+08:00 Victor Darras <notifications@github.com>:

> Hi, it seems that the plugin is not working on the last version of Sketch,
> I didn't use it before so it's maybe my fault. I'll try to read the plugin
> code later, to see if I can help you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maundytime/sketch-9patch/issues/1>.
>



-- 
Best,
Catt Liu

**Comment by maundytime** [comment]
How to use:

1. Put your layers in artboards. Each artboard would be export one PNG file.

2. Rename the artboard as you want, and no need to add ".9" or ".9.png".

3. Select one or more artboards, run the plugin, then you find PNG file on your desktop. It woud be in a file fold named like: "drawable-xhdpi" "drawable-xxhdpi" "drawable-xxxhdpi"...

* You can edit the mark layers in the layers group "$MarksGroup", adjust the mark area. Only notice: the plugin know an artboard has been marked already by recognize that if the name of top group is "$MarksGroup". So do not delete, rename the group "$MarksGroup", and keep it on top.
